### PR TITLE
Add three models to describe the data

### PR DESCRIPTION
**Pull request by statwonk**
This PR adds three models.

- p-spline model (a good basic smooth)
- poisson regression generalized linear model ("GLM")
- negative binomial GLM.

The `theta` parameter of the negative binomial indicates significant clustering of shootings. The parameter is bounded by 0 and Infinity. Insofar as it's close to Infinity, shootings are random. Insofar as it's close to 0, shootings are related. It could loosely be thought of as a mass shooting index.

A good next step would be to compare the fit of the negative binomial / p-spline and / or think of predictors of shootings that could be added. Predictors could help explain which factors relate to shootings.

### CODE REVIEW

**Comment by statwonk** [comment]
I broke out the analysis to a new workbook. I also tidied up the data munging operations by combining into a single dplyr pipeline. I used `tidyr::complete` to perform the "fill in NA dates" operation. I also split the analysis by police district to see which districts are having the most shootings.

districts

screen shot 2018-10-21 at 9 37 05 am

screen shot 2018-10-21 at 9 38 29 am

The rate of shootings in the Western district is about 2.6x that of the Central district.

**Comment by earthboundkid** [comment]
Whoa, this is awesome! I'm off work this week, but I'll ask the team to take a look.

**Comment by underthecurve** [comment]
thanks @statwonk!  I noticed you dealt with the "duplicates" issue by using Location+Date as the "unique identifier" ... I think the `Total.Incidents` column is the one to go with here in terms of number of incidents (for example, multiple shootings can occur at the same address/time.

```mutate(date = lubridate::mdy(CrimeDate),
       date = as.POSIXct(date, origin = "1970-01-01")) %>%
filter((Description == 'SHOOTING' | Description == 'HOMICIDE') & Weapon == 'FIREARM') %>%
  distinct(Location, date, .keep_all = TRUE) %>% # the data are rife with coding errors like duplicates.```

**Comment by statwonk** [comment]
> I noticed you dealt with the "duplicates" issue by using Location+Date as the "unique identifier" ...

that's right @underthecurve. Notice a better way? Thanks for the tip re: `Total.Incidents`!

Thank you @carlmjohnson!

I added two new views tonight. I fit Poisson distributions to each neighborhood. `lambda` is the [single param of a Poisson](https://en.wikipedia.org/wiki/Poisson_distribution#Probability_of_events_for_a_Poisson_distribution). It's the average number of events per interval. The inverse is the time between events. Then I plot the top 30 neighborhoods,

screen shot 2018-10-22 at 9 06 27 pm

We can look at a histogram for Sandtown-Winchester to check that the two make sense in context,

screen shot 2018-10-22 at 9 06 53 pm

**Pull request merged**
